May 7, 2020 11:05:07 AM EDT[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1869)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1718)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveAndLock(WMQSyncConsumerShadow.java:659)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.lockMessage(WMQMessageConsumer.java:870)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl._receiveBodyLock(JmsConsumerImpl.java:448)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:292)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:269)
                               : com.test.samples.mq.queue.Consumer.listenForMessages(Consumer.java:53)
                               : com.test.samples.mq.App.main(App.java:38)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1869)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1718)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveAndLock(WMQSyncConsumerShadow.java:659)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.lockMessage(WMQMessageConsumer.java:870)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl._receiveBodyLock(JmsConsumerImpl.java:448)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:292)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:269)
                               : com.test.samples.mq.queue.Consumer.listenForMessages(Consumer.java:53)
                               : com.test.samples.mq.App.main(App.java:38)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
May 7, 2020 11:05:07 AM EDT[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1869)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1718)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveAndLock(WMQSyncConsumerShadow.java:659)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.lockMessage(WMQMessageConsumer.java:870)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl._receiveBodyLock(JmsConsumerImpl.java:448)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:292)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:269)
                               : com.test.samples.mq.queue.Consumer.listenForMessages(Consumer.java:53)
                               : com.test.samples.mq.App.main(App.java:38)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1869)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1718)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveAndLock(WMQSyncConsumerShadow.java:659)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.lockMessage(WMQMessageConsumer.java:870)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl._receiveBodyLock(JmsConsumerImpl.java:448)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:292)
                               : com.ibm.msg.client.jms.internal.JmsConsumerImpl.receiveBody(JmsConsumerImpl.java:269)
                               : com.test.samples.mq.queue.Consumer.listenForMessages(Consumer.java:53)
                               : com.test.samples.mq.App.main(App.java:38)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
May 7, 2020 11:05:07 AM EDT[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:823)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:774)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:643)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:347)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl$SessionWrapper.close(JmsContextImpl.java:1954)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl.closeSession(JmsContextImpl.java:248)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl.close(JmsContextImpl.java:205)
                               : com.test.samples.mq.queue.Consumer.destroy(Consumer.java:45)
                               : com.test.samples.mq.App.main(App.java:39)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:823)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:774)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:643)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:347)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl$SessionWrapper.close(JmsContextImpl.java:1954)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl.closeSession(JmsContextImpl.java:248)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl.close(JmsContextImpl.java:205)
                               : com.test.samples.mq.queue.Consumer.destroy(Consumer.java:45)
                               : com.test.samples.mq.App.main(App.java:39)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:496)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1418)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1388)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQDISC(RemoteFAP.java:1521)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQDISC(RemoteFAP.java:1464)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQDISC(InterceptedJmqiImpl.java:431)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQDISC(ESEJMQI.java:396)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:811)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:774)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:643)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:347)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl$SessionWrapper.close(JmsContextImpl.java:1954)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl.closeSession(JmsContextImpl.java:248)
                               : com.ibm.msg.client.jms.internal.JmsContextImpl.close(JmsContextImpl.java:205)
                               : com.test.samples.mq.queue.Consumer.destroy(Consumer.java:45)
                               : com.test.samples.mq.App.main(App.java:39)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3798)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:566)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host '/127.0.0.1:1414 (dewey.newrelic.com)'. [1=-1,2=ffffffff,3=/127.0.0.1:1414 (dewey.newrelic.com),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:775)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:718)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:149)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
